### ISSUE TITLE
Incompatibility with 1.21.3+

### ISSUE THREAD

**Issue by leeineian** [TheVoidBlock/DontHideTheTooltip#1]
Take your time.

**Comment by TheVoidBlock** [comment]
I updated the mod to 1.21.3/4. You can find the jar on [Github releases](https://github.com/TheVoidBlock/DontHideTheTooltip/releases) or [Modrinth](https://modrinth.com/mod/donthidethetooltip/versions)

**Comment by leeineian** [comment]
Thank youuu dev 🙇
